refactor: update with respect to documentation
deepgram-devs/deepgram-deno-sdk pull request #21
Opened 2022-10-27 17:25 UTC by MoskalykA

2022-10-30 01:09 UTC, MichaelJolley requested changes
@MoskalykA thanks for this. There are a few changes needed before we can merge.

These feature additions should also affect some the `usageOptions` type and usage responses on some requests to the `/usage` endpoints.

2022-10-30 01:09 UTC, MichaelJolley commented on types/transcription/wordBase.ts
> -  punctuated_word?: string;
These properties do exist on the word. They should remain.

2022-10-30 01:09 UTC, MichaelJolley commented on types/transcription/prerecordedTranscriptionOptions.ts
> +   * @remarks Possible values are zh-CN, zh-TW, nl, en, en-AU, en-IN, en-NZ, en-GB, en-US, nl, fr, fr-CA, de, hi, hi-Latn, id, it, ja,
We add languages so often we probably want to just let them see the documentation for the most up to date list. Let's remove this remark.

2022-10-30 01:56 UTC, MoskalykA commented
Good 👍🏻

2023-01-05 15:12 UTC, briancbarrow approved these changes

2023-01-05 15:12 UTC, merged